// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.ProductAPI.Database;

#nullable disable

namespace Restaurant.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Restaurant.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Appetizer",
                            Description = "An Indian Appetizer",
                            ImageUrl = "https://bgmicrostorage.blob.core.windows.net/images/11[1].jpg",
                            Name = "Samosa",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            Description = "An Indian Appetizer",
                            ImageUrl = "https://bgmicrostorage.blob.core.windows.net/images/12[1].jpg",
                            Name = "Gobi Manchurian",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Appetizer",
                            Description = "An Indian Appetizer made with delicious spices",
                            ImageUrl = "",
                            Name = "Pani Pori",
                            Price = 7.9900000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
